// reactive-dough/src/components/layout.tsx
import Navbar from './navbar'
import Footer from './footer'

function Layout({children}: {children: any}) {
  return(
    <div className="h-screen flex flex-col justify-between">
      <Navbar/>
      <div className='flex grow justify-center content'>
        <div className="flex w-[1000px] py-4">
          <main className="w-full">{children}</main>
        </div>
      </div>
      <div className="flex justify-center py-2">
        <div className="min-w-[1000px] text-sm">
          <Footer/>
        </div>
      </div>
    </div>
  )
}

export default Layout

// slimdough/src/lib/components/layout.svelte
<script>
  import Navbar from './navbar.svelte'
  import Footer from './footer.svelte'

  let width = 1000
</script>

<div class='h-screen flex flex-col justify-between'>
  <Navbar/>
  <div class='flex grow justify-center content'>
    <div class="flex min-w-[1000px] py-4">
      <slot name='content'>This is the body</slot>
    </div>
  </div>
  <div class='flex justify-center py-2'>
    <div class="min-w-[1000px]">
      <Footer/>
    </div>
  </div>
</div>

<style>
.content {
  background-color: #F2F2F2
}
</style>
