// reactive-dough/src/components/navbar.tsx
import { Link } from 'react-router-dom'
import axios from 'axios'
import { useQuery } from '@tanstack/react-query'

export let navs = [
  { id: 0, endpoint: '/', page: 'Home' },
  //{ endpoint: '/about', page: 'About' },
  { id: 1, endpoint: '/contact', page: 'Contact' }
]

const isLoggedIn = async () => {
  try {
    const res = await axios.get("/api/public/isloggedin")
    return res.data
  } catch(err) {
    console.error(err)
  }
}

function Navbar() {
  const loggedInQuery = useQuery({
      queryKey: ['userLoggedIn'],
      queryFn: isLoggedIn,
      refetchOnWindowFocus: false,
      refetchInterval: 300000
  })


  return(
    <div className='flex justify-center shadow-lg'>
      <div className='flex justify-between py-2 w-[1000px] items-center'>
        <div className='text-lg font-bold'><Link to="/">satch3l</Link></div>
        <div className="flex space-x-4 items-center text-sm">
          <nav className='space-x-4'>
            {navs.map(nav => {
              return <Link to={nav.endpoint} key={nav.id}>{nav.page}</Link>
            })}
          </nav>
          {!loggedInQuery.isLoading && <AuthButton loggedIn={loggedInQuery.data.isLoggedIn}/>}
        </div>
      </div>
    </div>
  )
}

function AuthButton({loggedIn}: {loggedIn: boolean}) {
  if(loggedIn) {
    return <Link to="/myprofile">My Profile</Link>
  } else {
    return(
      <Link to="/authpage">
        <button className="bg-blue-500 text-white px-2 py-0.5 rounded-2xl shadow">Login / Signup</button>
      </Link>
    ) 
  }
}

export default Navbar

// slimdough/src/lib/components/navbar.svelte
<script>
  import { Link } from 'svelte-routing'
  import { createQuery } from '@tanstack/svelte-query'
  import axios from 'axios'

  import AuthButton from '../components/login_signup_button.svelte'

  const isLoggedIn = async () => {
    try {
      const res = await axios.get("/auth/isloggedin")
      return res.data
    } catch(err) {
      console.error(err)
      return err.response.data
    }
  }

  const refetchIntervalMs = 300000;
  const query = createQuery({
    queryKey: ['isLoggedIn'],
    queryFn: () => isLoggedIn(),
    refetchInterval: refetchIntervalMs,
    refetchOnWindowFocus: false
  })

  export let navs = [
    { endpoint: '/', page: 'Home' },
    //{ endpoint: '/about', page: 'About' },
    { endpoint: '/contact', page: 'Contact' }
  ]

</script>

<div class='flex justify-center shadow-lg'>
  <div class='flex justify-between py-2 w-[1000px] items-center'>
    <div class='text-lg font-bold'><Link to="/">knostash</Link></div>
    <div class="flex space-x-4 items-center text-sm">
      <nav class='space-x-4'>
        {#each navs as nav}
          <Link to={nav.endpoint}>{nav.page}</Link>
        {/each}
      </nav>
      {#if $query.isSuccess}
        <AuthButton loggedIn={$query.data.isLoggedIn}/>
      {/if}
    </div>
  </div>
</div>

<style>

</style>
